import React from "react";

const About = () => {
    return (
        <>
        <div className="jumbotron text-center mt-4 py-4">
            <h1>About Library Management Systems</h1>
            <p>Resize this responsive page to see the effect!</p> 
            </div>
  
        <div className="container mt-2">
        <div className="row d-flex justify-content-center align-items-center">
            <div className="col-sm-11 mx-4  card card-body p-4">
             <h3>About Us</h3>    
             <div className="py-3"></div>             
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris..
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...<br /><br />
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris..
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                                <br /><br />
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris..
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
             </p>           
                        </div>
                         <div className="py-4"></div>  
        </div>
        </div>

</>
    )
}

export default About;