import React from "react";

const Contact = () => {
    return (
        <>
       <div className="jumbotron text-center mt-4 py-4">
            <h1>Contact Us</h1>
            <p>Resize this responsive page to see the effect!</p> 
            </div>
  
        <div className="container mt-2">
        <div className="row d-flex justify-content-center align-items-center">
         <div className="col-sm-10 mx-4 py-4 mb-4 card  p-4">
             <div className="py-2"></div>             
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris..
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...<br /><br />
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
   
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                 <br /><br />
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris..
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
             </p>           
                        </div>
             <p className="col-sm-10 mx-4 py-4 mb-4 p-4"></p>  
        </div>
        </div>

</>
    )
}

export default Contact;